### ISSUE TITLE
Problem with the patcher.exe

### ISSUE THREAD

**Issue by Nekojinchik** [sayucchin/P2-EP-PSP#2]
When I run the patcher.exe it shuts down automatically. I tried to open patcher.exe using the command line and it showed this:
thread 'main' panicked at 'Please make sure the iso is the first argument.', src\main.rs:191:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
What should me do?

**Comment by Nekojinchik** [comment]
okay, i was stupid. sorry

**Comment by sayucchin** [comment]
I'm glad you got it to work
