### ISSUE TITLE
Soft lock after Tatsuya joins the party

### ISSUE THREAD

**Issue by thelaagy** [sayucchin/P2-EP-PSP#3]
I just can't go to the subway, Ulala don't let me in.

![image](https://user-images.githubusercontent.com/52465607/182263098-5619babf-4aae-41c3-8479-eb7fa354e249.png)

Here's my save file, I really don't know what to do. I read the old gamestop guide, I read the guide for the PSP version and I remember entering the subway dungeon straight away. What's happening?

[ULJM060810002.zip](https://github.com/sayucchin/P2-EP-PSP/files/9237993/ULJM060810002.zip)

**Comment by thelaagy** [comment]
nvm I'm dumb, I confused the lab with the subway

**Comment by sayucchin** [comment]
Glad you managed to proceed. Sent from my Galaxy
-------- Original message --------From: Laggy ***@***.***> Date: 02/08/2022  03:06  (GMT+02:00) To: sayucchin/P2-EP-PSP ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [sayucchin/P2-EP-PSP] Soft lock after Tatsuya joins the party (Issue #3) 
nvm I'm dumb, I confused the lab with the subway
