### ISSUE TITLE
[Question] "encrypted copy of most of the game data"

### ISSUE THREAD

**Issue by hyoretsu** [sayucchin/P2-EP-PSP#6]
> Why is the ISO half the size after patching?
>
> The original ISO contains an encrypted copy of most of the game data as Install Data. On UMD based games, there is an option copy this file to your PSP Memory Stick to reduce load times. For ISOs that are already on the Memory Stick, this is completely unnecessary. Removing it saves quite a bit of space.

Is that this `PSP_GAME/INSDIR/I020.DAT` file? Asking so I can better trim my PSP games, currently deleting these: (running on emulator)
```
PSP_GAME/ICON1.PMF
PSP_GAME/SYSDIR/BOOT.BIN
PSP_GAME/UPDATE
```

**Comment by eiowlta** [comment]
yes.  I think the entire INSDIR can relatively safely be deleted actually, although the bulk of it is the I020.DAT.

**Comment by hyoretsu** [comment]
> PSP_GAME/INSDIR/ will contain game defined files (usually DATA.BIN or similar) that would be installed on the memory stick if "Data Install" is selected.  Often encrypted to impede modding/cheating.

According to [this](https://www.romhacking.net/forum/index.php?topic=30899.0), yeah, the whole folder serves that purpose and can be deleted. Thanks
