### ISSUE TITLE
Camera angle changes skipped?

### ISSUE THREAD

**Issue by molberd** [sayucchin/P2-EP-PSP#7]
I noticed something happening when events/in-game cutscenes occur and the camera angle changes, like at the beginning when Maya goes to read the Joker letter. I expected it to be a smooth turn like in Innocent Sin, but instead it just jumps to the next camera angle. Is this intentional? An emulation issue? Or something else?

**Comment by sayucchin** [comment]
Not an emulation issue. This is the intentional camera angle and scene transition from the original game. You'll find the scene plays out the same way in the psx version.

**Comment by molberd** [comment]
Good to know. Thanks!
